version: '3.11'
services:
  postgres:
    image: 'postgres:15-alpine'
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  project:
    container_name: project
    command: 'poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    build: .
    volumes:
      - '.:/project'
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres
  celery_tasks:
    container_name: celery_tasks
    build: .
    command: poetry run celery -A celery_tasks.tasks worker --pool=solo --loglevel=info
    volumes:
      - '.:/project'
    depends_on:
      - redis
      - project
  redis:
    image: 'redis:6-alpine'
    restart: always
    env_file: .env
    command: redis-server
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - '6379'
    volumes:
      - 'redis-data:/data'
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project
volumes:
  postgres-data: null
  redis-data: null
