version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  project:
    container_name: project
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    build: .
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - redis
  celery_tasks:
    container_name: celery_tasks
    build: .
    command: poetry run celery -A celery_tasks.tasks worker --pool=solo --loglevel=info
    volumes:
      - .:/project
    depends_on:
      - redis
      - project
  celery_beat:
    container_name: celery_beat
    build: .
    command: poetry run celery -A celery_tasks.tasks beat --pool=solo --loglevel=info
    volumes:
      - .:/project
    depends_on:
      - redis
      - project